### PR TITLE
fix #3 publish woot model as a separate library with bintray

### LINKED ISSUE #3: Can factor out the core as a sperate lib
Can you factor out the core as a lib where a shared string / data structure is edited by multiple thread?

### PR DESCRIPTION
**Pull request by MasseGuillaume**
I published to my personal repo for now

```
resolvers += "masseguillaume" at "http://dl.bintray.com/content/masseguillaume/maven"
libraryDependencies += "com.dallaway.richard" %%% "woot-model" % "0.1.0"
```

It look like there is unresolved issues with ScalaCheck in scalaJS see https://github.com/d6y/wootjs/issues/5

### CODE REVIEW

**Comment by d6y** [comment]
Out of interest @MasseGuillaume what are you planning to use WOOT with?

**Comment by MasseGuillaume** [comment]
http://scalakata.com :-)

**Comment by d6y** [comment]
That would be very cool!

**Comment by MasseGuillaume** [comment]
Just got it working ;-). I will release it live next monday on scalakata.com via reddit.com/r/scala

demo

the hardest part was to think backward lol
https://github.com/MasseGuillaume/ScalaKata2/blob/master/webapp/js/src/main/scala/com.scalakata/Collaborative.scala#L106-L112

when you are doing paste operations where text is removed, you need to remove in the reverse direction and then add. I think it's a bug, because you should be able to [delete forward](https://github.com/d6y/wootjs/blob/d9cb08ae179e48db2b50e2535a573f37edb3aad2/wootModel/shared/src/main/scala/woot/Woot.scala#L270).

Another difficult part is mapping woojs model to the editor. Maybe some helper functions to do batching operations would help: `replace(from: Int, to: Int, text: String)`, `delete(from: Int, to: Int)`, etc

**Comment by d6y** [comment]
Great stuff @MasseGuillaume!

I'm not sure what you mean by a "paste operations where text is removed". If there's something you need specific help with, happy to hangout or gitter chat about it.

In the WOOT model itself the order doesn't matter (if it does, it's a bug).  The hard part is figuring out how to translate a WOOT operation into a change in the editor.

Batch/bulk operations (paste, cut) are a weakness for WOOT: you end up having to turn them into individual changes for WOOT to apply them, which can be slow.  Adding `replace` and `delete` would be possible, it would end up as sequence of operations eventually (to keep the WOOT algorithm's guarantees). But if that'd be useful, I can look at it.

**Comment by MasseGuillaume** [comment]
> I'm not sure what you mean by a "paste operations where text is removed"

given the following in your clipboard

```
___
______
___
```

select from line 0, column 2 until line 2 column 3 and paste

```
xxxxx          xx___
xxxxx   -->    _____
xxxxx          ___xx
```

In this case you need to insert and delete multiple chars. Initially I would add then delete in the foward order. I found out it only works if you delete reverse then add. I will create a test case for both.

**Pull request merged**
